#!/bin/bash

docker run -d cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMmVkNzRmZmIyYTU2YTIwN2QwZTc5Yjg3MTZkNjExYmQiLCJ0IjoiNWYwMzBkZDMtYTVhYi00MDdmLWEwOTctMDgwZTQwNGQ0YThlIiwicyI6IlpEZGhPVFF3TkdZdE9XWmtZUzAwT0dKbExUZzFOMlV0TnprM1l6TXdPV1F4TmpabCJ9
