#!/bin/bash

docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMmVkNzRmZmIyYTU2YTIwN2QwZTc5Yjg3MTZkNjExYmQiLCJ0IjoiNWYwMzBkZDMtYTVhYi00MDdmLWEwOTctMDgwZTQwNGQ0YThlIiwicyI6Ik56bGhOVEJoTWprdFkyWTNOeTAwWTJZeUxUazFaR1l0WldOak0yRXpORGRoTldGaiJ9
